### ISSUE TITLE
屏蔽所有诈骗犯功能对部分账号失效

### ISSUE THREAD

**Issue by aoxu** [daymade/Twitter-Block-Porn#11]
![image](https://github.com/daymade/Twitter-Block-Porn/assets/3169925/0bee017a-c8d8-49c9-a10b-c9ca61de789b)
如图
我点过「屏蔽所有诈骗犯」后，往下滚动了2屏左右，就看到有几个没屏蔽的账号。
重试过屏蔽，重开过这个列表页，问题依旧。

**Comment by daymade** [comment]
有极少数账号走接口拉黑不了, 目前还不知道为啥, 我会看一下具体原因, 但大概率是马斯克没妈

**Comment by daymade** [comment]
先关闭了， 有问题可以再打开
