### ISSUE TITLE
大量極度噁心NSFW帳號列表 請幫忙加入腳本（包括少量無意義、詐騙、無限重複貼文等）

### ISSUE THREAD

**Issue by fk8438** [daymade/Twitter-Block-Porn#141]
您好，

這裡下面有不少極度噁心NSFW帳號列表。**極度噁心**，建議不要點入，直接放入腳本就可以了。我具體的檢查方法為：在推特上找到一個黃推，加入列表之後再去看有沒有轉推或者關注用戶，然後將那批用戶也加入列表，接著尋找他們的轉推等，以此類推。

列表還有包括少量無意義、詐騙、無限重複貼文等，希望可以一併加入，謝謝。

下面是列表帳號的@，由於時間限制，帳號名字沒有填充，深感抱歉：

@miamia1llIa
@AdelaKingsley88
@nuannaun2222
@green6l2l3
@chacha666de
@baicha2003
@Naimes121
@EmilyZhTo
@ShadCathey3
@LuMingJiangaa
@LuMingJiange
@DouDui74860
@chacha66de
@OrlandoRud73410
@elonmusk
@ShadCathey3
@fuxiaoqingf
@fuxiaoqingf_ 
@xiokeai123
@DeboraC8921447
@mahikumari5234
@CarlotaC92209
@JenniferHu3186
@czO41128
@CTJlNGgao
@xiaomei6656
@bubaoec
@shaob1024
@MXXI00N

謝謝您的配合，祝閣下諸事順利。

Morris198

**Comment by AlphaCatMeow** [comment]
夹私货是吧，把伊隆马放中间别人就看不到了吗？
