### ISSUE TITLE
请问黑名单列表是不是停止更新了呢？

### ISSUE THREAD

**Issue by go522000** [daymade/Twitter-Block-Porn#171]
我刚刚重新安装了1.5.5版本，但黑名单列表与去年一样只更新到7。
请问是不是停止更新了呢？
还是我这边哪里操作有问题？

**Comment by daymade** [comment]
> 我刚刚重新安装了1.5.5版本，但黑名单列表与去年一样只更新到7。
> 请问是不是停止更新了呢？
> 还是我这边哪里操作有问题？

没问题，没有新增列表，但列表一直在加人。

有时间我会写个功能把新增了多少人显示出来🙊
