### ISSUE TITLE
所有屏蔽请求均返回404

### ISSUE THREAD

**Issue by wwbfred** [daymade/Twitter-Block-Porn#172]
使用插件时所有的屏蔽请求都会返回404，请求如图。
![Snipaste_2024-03-20_22-50-19](https://github.com/daymade/Twitter-Block-Porn/assets/4551347/101818d3-4152-44bd-a4f8-40d20c96805b)
载荷例如user_id=1633746269150773248，
响应为{"errors":[{"code":50,"message":"User not found."}]}。
另外账号为新注册账号，请问是否与此有关？

**Comment by daymade** [comment]
感谢反馈，有部分404是正常现象。

你注意看下是不是所有请求都404，因为有一部分诈骗账号已经被封了，所以拉黑它们的请求就是会返回404的。

**Comment by wwbfred** [comment]
是的，所有请求都是404，所有清单点击"屏蔽所有诈骗犯"均没有任何效果，包括加急清单。
我认为这与账号的注册时间长短有关，在一个全新的账号下操作应该可以复现这一现象。

**Comment by daymade** [comment]
点击屏蔽按钮后，在 console 搜过这个日志，关键字：`blockedIds:`

<img width="618" alt="image" src="https://github.com/daymade/Twitter-Block-Porn/assets/4291901/706b1c84-89aa-40cf-ab1d-05aaf32a042e">


如果有值，说明在同一个浏览器里，你的旧twitter号已经用本插件屏蔽过了很多黄推，新twitter号就不会再次屏蔽了（这是bug也是feature）。

目前没处理一个浏览器里有多个账号的情况，如果是上述情况，你试下能不能卸载插件重新安装来解决这个问题。

**Comment by wwbfred** [comment]
blockedIds是有值的。关于多账号的问题，我之前已经完全退出旧帐号了，没有一个环境下多账号并存的情况。
有一点忘了提了，就是该账号在第一次使用脚本时成功屏蔽了10多个账户，之后所有的请求返回的都是404。
另外我在重装了JS脚本后又在隐身模式下做了测试，这个问题依旧存在。

**Comment by daymade** [comment]
@wwbfred 现在怎么样了？

**Comment by wwbfred** [comment]
我关闭了其他所有扩展和脚本，现在依然是404，怀疑是Twitter对某些账号调用API做出的限制，新注册账号马上使用脚本发送大量API调用直接被风控了。
请问模拟点击Block按钮时发送的请求是否存在障碍，这个方法理论上兼容性更好。

**Comment by daymade** [comment]
长时间无更新，先关闭issue，如果有问题请再反馈，谢谢
