### ISSUE TITLE
右上角没有“屏蔽” 按钮

### ISSUE THREAD

**Issue by jeson106** [daymade/Twitter-Block-Porn#18]
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/90f4d32e-37f8-4f2d-b866-19d14fecb0ec)
您好，首先感谢您开发了此脚本插件。
有个问题，安装后，查看用户列表，右上角没有出现如上图所示右上角“屏蔽” 按钮，请问是什么原因，谢谢!

**Comment by jeson106** [comment]
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/c8b4cefe-b02a-4161-a09a-c512ed179d8d)

**Comment by jeson106** [comment]
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/3fb1e46c-09eb-417a-9d7b-0eef92abb67c)

**Comment by daymade** [comment]
请尝试使用最新版的 Chrome 安装脚本，重试查看问题是否解决。

如果还有问题，请提供以下信息帮助定位原因：

- 系统：Windows/macOS
- 系统版本：Windows 11/10
- 浏览器：Chrome/Firefox/Edge
- 浏览器版本：Chrome 117.0.x

**Comment by jeson106** [comment]
> 请尝试使用最新版的 Chrome 安装脚本，重试查看问题是否解决。
> 
> 如果还有问题，请提供以下信息帮助定位原因：
> 
> * 系统：Windows/macOS
> * 系统版本：Windows 11/10
> * 浏览器：Chrome/Firefox/Edge
> * 浏览器版本：Chrome 117.0.x

您好：
系统: win10
浏览器: chrome 116.0.5845.180（正式版本） （64 位）
已安装最新版本脚本
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/92e5e83e-f29d-434a-8436-e84df1a55ef1)
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/cf1684a7-ea8f-4471-856b-cc8a5eec0bbf)

**Comment by daymade** [comment]
> 
> 
> 
> > 请尝试使用最新版的 Chrome 安装脚本，重试查看问题是否解决。
> > 
> > 如果还有问题，请提供以下信息帮助定位原因：
> > 
> > * 系统：Windows/macOS
> > * 系统版本：Windows 11/10
> > * 浏览器：Chrome/Firefox/Edge
> > * 浏览器版本：Chrome 117.0.x
> 
> 您好：
> 系统: win10
> 浏览器: chrome 116.0.5845.180（正式版本） （64 位）
> 已安装最新版本脚本
> ![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/92e5e83e-f29d-434a-8436-e84df1a55ef1)
> ![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/cf1684a7-ea8f-4471-856b-cc8a5eec0bbf)
> 
> 

请打开开发者工具窗口，保持开发者工具打开状态，刷新页面，看一下 Console 和 Network 标签页有没有红色的异常错误，比如 Console 里有可能有一些 js 代码执行报错，Network 里有可能有网络资源没有加载成功，如果可以的话在这贴出以上两个标签的完整截图。


可通过三种方式打开Chrome 开发者工具：

在Chrome 菜单中选择更多工具> 开发者工具
在页面元素上右键点击，选择“检查”
使用快捷键Ctrl+Shift+I（Windows）或Cmd+Opt+I（Mac）

默认情况下，它将在 DevTools 中打开 Console （控制台）面板。 打开 Console 面板之后，只需要点击 Network ，就可以切换到网络面板。

**Comment by daymade** [comment]
> > > > 请尝试使用最新版的 Chrome 安装脚本，重试查看问题是否解决。
> > > > 如果还有问题，请提供以下信息帮助定位原因：
> > > > 
> > > > * 系统：Windows/macOS
> > > > * 系统版本：Windows 11/10
> > > > * 浏览器：Chrome/Firefox/Edge
> > > > * 浏览器版本：Chrome 117.0.x
> > > 
> > > 
> > > 您好：
> > > 系统: win10
> > > 浏览器: chrome 116.0.5845.180（正式版本） （64 位）
> > > 已安装最新版本脚本
> > > ![image](https://user-images.githubusercontent.com/106364995/266239717-92e5e83e-f29d-434a-8436-e84df1a55ef1.png)
> > > ![image](https://user-images.githubusercontent.com/106364995/266239893-cf1684a7-ea8f-4471-856b-cc8a5eec0bbf.png)
> > 
> > 请打开开发者工具窗口，保持开发者工具打开状态，刷新页面，看一下 Console 和 Network 标签页有没有红色的异常错误，比如 Console 里有可能有一些 js 代码执行报错，Network 里有可能有网络资源没有加载成功，如果可以的话在这贴出以上两个标签的完整截图。
> > 
> > 可通过三种方式打开Chrome 开发者工具：
> > 
> > * 在Chrome 菜单中选择更多工具> 开发者工具
> > * 在页面元素上右键点击，选择“检查”
> > * 使用快捷键Ctrl+Shift+I（Windows）或Cmd+Opt+I（Mac）
> > 
> > 默认情况下，它将在 DevTools 中打开 Console （控制台）面板。 打开 Console 面板之后，只需要点击 Network ，就可以切换到网络面板。
> 
> 您好，按您说的操作，的确有二个错误
> ![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/259daeab-d972-41c9-b034-bcebdb965c4d)
> 

这两个错误应该和问题无关，方便上下滚动一下屏幕，看看还有没有其他错误吗？
另外，如果能把 Network 下面的全部请求截图更好。

注意这两个选项卡下可能需要多张截图才能看到完整的上下文信息，这对我排查问题很有帮助，谢谢。

**Comment by jeson106** [comment]
> > > > > 请尝试使用最新版的 Chrome 安装脚本，重试查看问题是否解决。
> > > > > 如果还有问题，请提供以下信息帮助定位原因：
> > > > > 
> > > > > * 系统：Windows/macOS
> > > > > * 系统版本：Windows 11/10
> > > > > * 浏览器：Chrome/Firefox/Edge
> > > > > * 浏览器版本：Chrome 117.0.x
> > > > 
> > > > 
> > > > 您好：
> > > > 系统: win10
> > > > 浏览器: chrome 116.0.5845.180（正式版本） （64 位）
> > > > 已安装最新版本脚本
> > > > ![image](https://user-images.githubusercontent.com/106364995/266239717-92e5e83e-f29d-434a-8436-e84df1a55ef1.png)
> > > > ![image](https://user-images.githubusercontent.com/106364995/266239893-cf1684a7-ea8f-4471-856b-cc8a5eec0bbf.png)
> > > 
> > > 
> > > 请打开开发者工具窗口，保持开发者工具打开状态，刷新页面，看一下 Console 和 Network 标签页有没有红色的异常错误，比如 Console 里有可能有一些 js 代码执行报错，Network 里有可能有网络资源没有加载成功，如果可以的话在这贴出以上两个标签的完整截图。
> > > 可通过三种方式打开Chrome 开发者工具：
> > > 
> > > * 在Chrome 菜单中选择更多工具> 开发者工具
> > > * 在页面元素上右键点击，选择“检查”
> > > * 使用快捷键Ctrl+Shift+I（Windows）或Cmd+Opt+I（Mac）
> > > 
> > > 默认情况下，它将在 DevTools 中打开 Console （控制台）面板。 打开 Console 面板之后，只需要点击 Network ，就可以切换到网络面板。
> > 
> > 
> > 您好，按您说的操作，的确有二个错误
> > ![image](https://user-images.githubusercontent.com/106364995/266269959-259daeab-d972-41c9-b034-bcebdb965c4d.png)
> 
> 这两个错误应该和问题无关，方便上下滚动一下屏幕，看看还有没有其他错误吗？ 另外，如果能把 Network 下面的全部请求截图更好。
> 
> 注意这两个选项卡下可能需要多张截图才能看到完整的上下文信息，这对我排查问题很有帮助，谢谢。

您好，netowork下的全部截图，图片可能比较长，谢谢
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/0110af28-968e-4c8d-820f-9dd30fafa6a1)

**Comment by jeson106** [comment]
console下面的完整截图
![image](https://github.com/daymade/Twitter-Block-Porn/assets/106364995/a5bb93fc-450e-4fa5-9d84-10089d3aeef9)

**Comment by daymade** [comment]
@jeson106 谢谢，我会尽快看下

**Comment by daymade** [comment]
😂仍然没有头绪

**Comment by s5s5** [comment]
换下梯子节点，试试
升级到最新版本 1.5.1，再试试

**Comment by daymade** [comment]
@jeson106 请问你现在是否仍然遇到这个问题?
