### ISSUE TITLE
补充黑名单

### ISSUE THREAD

**Issue by Walessky** [daymade/Twitter-Block-Porn#19]
https://twitter.com/Hornysister5；https://twitter.com/luchuaihaoz9；https://twitter.com/backjessie0；https://twitter.com/BrunoNep1；https://twitter.com/dmkm650flp

**Comment by lukedumboy** [comment]
https://twitter.com/j96fbcwacnsw3ry

**Comment by daymade** [comment]
感谢各位, 以上已全部添加到 [Scammers 黄推诈骗犯 ③](https://twitter.com/i/lists/1699049983159259593),
