### ISSUE TITLE
黄推诈骗名单19人  今日收集9.8

### ISSUE THREAD

**Issue by Neneka-hash** [daymade/Twitter-Block-Porn#20]
黄推诈骗名单
https://twitter.com/NellyMiddl78382
https://twitter.com/BmiRi033
https://twitter.com/Derlimishu
https://twitter.com/eva006906
https://twitter.com/taohua_88
https://twitter.com/BraylonCro86577
https://twitter.com/bhabhi78
https://twitter.com/zhanglele661
https://twitter.com/EileenC65845934
https://twitter.com/souzan_10
https://twitter.com/YeLin12453119
https://twitter.com/ShawnSturgeon8
https://twitter.com/HarlanWat15
https://twitter.com/Merieli10
https://twitter.com/ErinJoyce457909
https://twitter.com/apjob681mdlg
https://twitter.com/MarkDav32818554
https://twitter.com/GXimqn
https://twitter.com/ReginaAdol27734

**Comment by daymade** [comment]
已添加到 [Scammers 黄推诈骗犯 ③](https://twitter.com/i/lists/1699049983159259593), 感谢
