### ISSUE TITLE
在评论区黄推和打广告的

### ISSUE THREAD

**Issue by Desktea** [daymade/Twitter-Block-Porn#24]
https://twitter.com/MarkDav32818554
https://twitter.com/mccullough_nita
https://twitter.com/Dateflix_
https://twitter.com/TP30781303
https://twitter.com/GXimqn
https://twitter.com/BmiRi033
https://twitter.com/L0vezon
https://twitter.com/Itslusty_0
https://twitter.com/Qu_een_yu
https://twitter.com/goodminess
https://twitter.com/_fruit_orange
https://twitter.com/C0upleLove
https://twitter.com/BraXnxx
https://twitter.com/NelsonZ40974872
https://twitter.com/as13384
https://twitter.com/eva006906
https://twitter.com/xiaohan8888888
https://twitter.com/we169668C/with_replies
https://twitter.com/MallikaM11
https://twitter.com/CathyRhys874136
https://twitter.com/ZT73181442

https://twitter.com/YoY009222

**Comment by Desktea** [comment]
https://twitter.com/TP30781303
https://twitter.com/pangyuanyua
https://twitter.com/18PostedVideo
https://twitter.com/Xnz715
https://twitter.com/ihaep115xnq
https://twitter.com/we169668C
https://twitter.com/DamarionC90698

**Comment by Desktea** [comment]
https://twitter.com/Banmianriji01
https://twitter.com/zenskOo
https://twitter.com/jsbakahajav1
https://twitter.com/ryanhslowhn

**Comment by Desktea** [comment]
https://twitter.com/Chuimian_1
https://twitter.com/fzrrd1774xqvmi
https://twitter.com/renyusanqiansui
https://twitter.com/xxaayymjx
https://twitter.com/margaret_i46729
https://twitter.com/mdm76cjypd

**Comment by Desktea** [comment]
https://twitter.com/charley_ju21590

**Comment by Desktea** [comment]
https://twitter.com/tycum1990

**Comment by Desktea** [comment]
https://twitter.com/Nandastr6
https://twitter.com/Blw61983
https://twitter.com/new_stronger
https://twitter.com/sampson_pe11894
https://twitter.com/ccc04691156
https://twitter.com/charley_ju21590
https://twitter.com/gatv3558wlxh
https://twitter.com/XSM_12
https://twitter.com/tiktoklovee04
https://twitter.com/Princes_ji

**Comment by daymade** [comment]
Extracted Twitter usernames from the GitHub page:

MarkDav32818554, mccullough_nita, Dateflix_, TP30781303, GXimqn, BmiRi033, L0vezon, Itslusty_0, Qu_een_yu, goodminess, _fruit_orange, C0upleLove, BraXnxx, NelsonZ40974872, as13384, eva006906, xiaohan8888888, we169668C, MallikaM11, CathyRhys874136, ZT73181442, YoY009222, pangyuanyua, 18PostedVideo, Xnz715, ihaep115xnq, DamarionC90698, Banmianriji01, zenskOo, jsbakahajav1, ryanhslowhn, Chuimian_1, fzrrd1774xqvmi, renyusanqiansui, xxaayymjx, margaret_i46729, mdm76cjypd, charley_ju21590, tycum1990, Nandastr6, Blw61983, new_stronger, sampson_pe11894, ccc04691156, gatv3558wlxh, XSM_12, tiktoklovee04, Princes_ji

Note: Some usernames might be aliases or decoys, as the page is about blocking certain Twitter accounts.

已添加到 https://twitter.com/i/lists/1702721627287371907
