### ISSUE TITLE
屏蔽未生效

### ISSUE THREAD

**Issue by Yelrahc-sudo** [daymade/Twitter-Block-Porn#26]
第一次打开共享列表，点击屏蔽所有诈骗犯，但第二次打开同一共享列表，里面的账号并未显示屏蔽呀

**Comment by Yelrahc-sudo** [comment]
刚刚接着测试了一下，几个版本，发现未生效是最新版本的v1.4.0. 我的浏览器是chrome

**Comment by daymade** [comment]
这个问题我不太好复现，你方便帮忙定位下原因吗？ 

你可以在开发者工具里看下 console 和 network 里有没有什么异常。

**Comment by Yelrahc-sudo** [comment]
版本1.4.0, 在点击【屏蔽所有诈骗犯】后，在控制台追踪到以下信息，网络里状态码正常为200
![控制台输出](https://github.com/daymade/Twitter-Block-Porn/assets/59365026/5b06cd8c-522f-46f4-a19b-bbbf460893a8)

**Comment by daymade** [comment]
> 版本1.4.0, 在点击【屏蔽所有诈骗犯】后，在控制台追踪到以下信息，网络里状态码正常为200
> ![控制台输出](https://github.com/daymade/Twitter-Block-Porn/assets/59365026/5b06cd8c-522f-46f4-a19b-bbbf460893a8)
> 

卸载重装下插件试试，这个日志表示你已经成功屏蔽过这些 id 了，所以不会再屏蔽。你是不是有多个账号？

目前没有做多账号支持，可能一个账号拉黑以后，切换另外一个账号在同一个浏览器里就无法再次拉黑了。

**Comment by Yelrahc-sudo** [comment]
好的，我試試，感謝👍
