### ISSUE TITLE
提议：有一位朋友来维护新的列表

### ISSUE THREAD

**Issue by daymade** [daymade/Twitter-Block-Porn#32]
参照现存的列表 [Scammers 黄推诈骗犯 ③](https://twitter.com/i/lists/1699049983159259593),  新列表的名字定义为： Scammers 黄推诈骗犯 ④

需要你做的事情：

1. 建议用一个小号来新建一个 List 列表， 将现存的 issue 里的诈骗号都添加到这个列表里去。
2. 维护这个列表，遇到新的账号时，添加到这个列表里来。 
3. 直到马斯克限制这个列表，不允许再往里添加新的账号了， 这个时候我们会新建一个 “Scammers 黄推诈骗犯 ⑤"

我会把这个列表④也添加到插件的入口。

这样做有几个好处：
1. 将列表的维护工作交给社区，我专注在插件新功能的代码编写上，目前有几个高优先级的功能来不及实现，比如自动拉黑新账号， 快速举报等功能。
2. 我可以使用插件来拉黑这个列表，我之前不能拉黑诈骗号，因为拉黑后会把诈骗号自动移出列表。

如果有其他想法或建议， 欢迎与我联系。

**Comment by CMEPCBHG** [comment]
我愿意维护，不过我也是这几天才刚开始用这个脚本，更详细的原理、逻辑、维护（操作）方法不是很明白。但我愿意讨论和学习。

**Comment by daymade** [comment]
> 我愿意维护，不过我也是这几天才刚开始用这个脚本，更详细的原理、逻辑、维护（操作）方法不是很明白。但我愿意讨论和学习。

谢谢，不过我上面没说清楚，理论上只需要用推特创建和维护列表就可以，在网页版和手机端都可以操作，我会引导用户跳转到你创建的列表去拉黑。

**Comment by CMEPCBHG** [comment]
> > 我愿意维护，不过我也是这几天才刚开始用这个脚本，更详细的原理、逻辑、维护（操作）方法不是很明白。但我愿意讨论和学习。
> 
> 谢谢，不过我上面没说清楚，理论上只需要用推特创建和维护列表就可以，在网页版和手机端都可以操作，我会引导用户跳转到你创建的列表去拉黑。
> 
> 类似这位朋友整理的列表 https://twitter.com/liruqi/status/1693138325190869074?t=jfvDVa8cUcRRfvnNNqYECA&s=19

我的列表里面的名单与前面的名单重复与否有没有影响呢？列表内的用户数量有没有上限呢？

**Comment by CMEPCBHG** [comment]
列表链接
https://twitter.com/i/lists/1701961893261234606?s=20

**Comment by CMEPCBHG** [comment]
奇怪，是因为我的账号刚创建，所以我无法用脚本一键拉黑吗？我试了很多次，都没法拉黑屏蔽现有的列表内的账号。

**Comment by daymade** [comment]
> > > 我愿意维护，不过我也是这几天才刚开始用这个脚本，更详细的原理、逻辑、维护（操作）方法不是很明白。但我愿意讨论和学习。
> > 
> > 谢谢，不过我上面没说清楚，理论上只需要用推特创建和维护列表就可以，在网页版和手机端都可以操作，我会引导用户跳转到你创建的列表去拉黑。
> > 
> > 类似这位朋友整理的列表 https://twitter.com/liruqi/status/1693138325190869074?t=jfvDVa8cUcRRfvnNNqYECA&s=19
> 
> 我的列表里面的名单与前面的名单重复与否有没有影响呢？列表内的用户数量有没有上限呢？

没有影响，重复拉黑会被 Twitter 忽略，不过避免重复可以减少一些拉黑次数

**Comment by CMEPCBHG** [comment]
不好意思，最近事情有点多，比较忙，这个列表估计要下星期一才能正式开始添加用户。

**Comment by daymade** [comment]
> 不好意思，最近事情有点多，比较忙，这个列表估计要下星期一才能正式开始添加用户。

好的，给你留了一个④的位置😁

**Comment by CMEPCBHG** [comment]
可以开始了，今晚先添加一些账户，我尽量不重复，会随时更新其他列表的账户屏蔽之后，再把非重复的添加到我的列表。

**Comment by CMEPCBHG** [comment]
> 可以开始了，今晚先添加一些账户，我尽量不重复，会随时更新其他列表的账户屏蔽之后，再把非重复的添加到我的列表。

尽快上线我就可以提高效率了。

**Comment by CMEPCBHG** [comment]
> > 不好意思，最近事情有点多，比较忙，这个列表估计要下星期一才能正式开始添加用户。
> 
> 好的，给你留了一个④的位置😁

大佬，把我的4加入脚本吧

**Comment by CMEPCBHG** [comment]
> > > > 不好意思，最近事情有点多，比较忙，这个列表估计要下星期一才能正式开始添加用户。
> > > 
> > > 
> > > 好的，给你留了一个④的位置😁
> > 
> > 
> > 大佬，把我的4加入脚本吧
> 
> 感谢你花时间维护这个列表，但这个列表问题比较大，里面有一些误判？ 比如
> 
> 老实本分的黄推: https://twitter.com/wanwanxbc
> 
> 正常推友： https://twitter.com/jjgfscbd
> 
> 误判对推友的影响比较大，需要谨慎添加

明白了，之后我会更多斟酌。

**Comment by CMEPCBHG** [comment]
更具体一点的话，要怎么分辨呢？因为我也确实是在反共大V的评论区看到的

**Comment by aoxu** [comment]
> 更具体一点的话，要怎么分辨呢？因为我也确实是在反共大V的评论区看到的

我提供一点经验，诈骗黄推肯定会在别人的推文下面发回复，并且回复一定是与推文无关的 spam 内容。
这里面最关键的一点就是：诈骗黄推的回复内容一定与楼主的推文无关，因为这些账号都是机器人批量自动化运作，回复什么都是事先安排好的，而不是阅读推文后分析内容回复（也许ta们的幕后AI还没进化到这一步）。并且回复的内容本身往往具有引流性质，目的是吸引你点ta的主页去看。

**Comment by CMEPCBHG** [comment]
按照上面提到的经验，我当前给列表添加的十个用户，是否符合呢？是的话我就按照这个方式来添加了，我都是在评论区找的。之前的一些用户应该是在issue内其他朋友提供的，被我添加了进去。

**Comment by daymade** [comment]
> 按照上面提到的经验，我当前给列表添加的十个用户，是否符合呢？是的话我就按照这个方式来添加了，我都是在评论区找的。之前的一些用户应该是在issue内其他朋友提供的，被我添加了进去。

感谢，这十个账号应该没有误判的，但没有必要管这些每日大赛下面的账号， 只需要添加在正常大 V 评论区恶意引流的那一批诈骗号即可，搞黄色的如果在每日大赛下面就不用浪费名额给他们， 因为拉黑这批人并不会提升刷推体验。

**Comment by CMEPCBHG** [comment]
> > 按照上面提到的经验，我当前给列表添加的十个用户，是否符合呢？是的话我就按照这个方式来添加了，我都是在评论区找的。之前的一些用户应该是在issue内其他朋友提供的，被我添加了进去。
> 
> 感谢，这十个账号应该没有误判的，但没有必要管这些每日大赛下面的账号， 只需要添加在正常大 V 评论区恶意引流的那一批诈骗号即可，搞黄色的如果在每日大赛下面就不用浪费名额给他们， 因为拉黑这批人并不会提升刷推体验，在保证评论区体验的情况下，黑名单数量越少越好。

我就是在大V评论区找的XD

**Comment by CMEPCBHG** [comment]
> > > 按照上面提到的经验，我当前给列表添加的十个用户，是否符合呢？是的话我就按照这个方式来添加了，我都是在评论区找的。之前的一些用户应该是在issue内其他朋友提供的，被我添加了进去。
> > 
> > 
> > 感谢，这十个账号应该没有误判的，但没有必要管这些每日大赛下面的账号， 只需要添加在正常大 V 评论区恶意引流的那一批诈骗号即可，搞黄色的如果在每日大赛下面就不用浪费名额给他们， 因为拉黑这批人并不会提升刷推体验，在保证评论区体验的情况下，黑名单数量越少越好。
> 
> 我就是在大V评论区找的XD

接下来我会只留意大V评论区比较影响刷推的头部评论，仔细甄别之后再添加到列表。

**Comment by daymade** [comment]
> > > 按照上面提到的经验，我当前给列表添加的十个用户，是否符合呢？是的话我就按照这个方式来添加了，我都是在评论区找的。之前的一些用户应该是在issue内其他朋友提供的，被我添加了进去。
> > 
> > 
> > 感谢，这十个账号应该没有误判的，但没有必要管这些每日大赛下面的账号， 只需要添加在正常大 V 评论区恶意引流的那一批诈骗号即可，搞黄色的如果在每日大赛下面就不用浪费名额给他们， 因为拉黑这批人并不会提升刷推体验，在保证评论区体验的情况下，黑名单数量越少越好。
> 
> 我就是在大V评论区找的XD

哈哈， 那应该是这些账号在两边都发了， 你有时间帮忙审核现有 issue 里的举报吗？ 

参考步骤:
1. 把现有的 5 个共享黑名单（1，2，3，5，加急）都屏蔽完
2. 审核 open 状态的 issue 里的账号，打开账号主页查看简介，回复
3. 如果符合（在大 V 评论区 + 恶意引流 + 缅北 Cosplay 诈骗）这几个特征就可以添加到列表 4 里。 
4. 一个 issue 里的账号全部审核完毕后， 你可以 @ 我过来关 issue。 

感谢你付出的时间和精力！

**Comment by aoxu** [comment]
再补充一条特征：诈骗黄推多数都会在自己的个人简介里写上 Telegram 联系方式，因为这是ta们诈骗的主要联系方式，算是必经之路吧。少数更隐蔽的会说「私信领福利」，但其实私信还是会发一个 Telegram 联系方式，这样只是从个人简介页面看不到了而已。

**Comment by CMEPCBHG** [comment]
> 再补充一条特征：诈骗黄推多数都会在自己的个人简介里写上 Telegram 联系方式，因为这是ta们诈骗的主要联系方式，算是必经之路吧。少数更隐蔽的会说「私信领福利」，但其实私信还是会发一个 Telegram 联系方式，这样只是从个人简介页面看不到了而已。

get！

**Comment by CMEPCBHG** [comment]
> > > > 按照上面提到的经验，我当前给列表添加的十个用户，是否符合呢？是的话我就按照这个方式来添加了，我都是在评论区找的。之前的一些用户应该是在issue内其他朋友提供的，被我添加了进去。
> > > 
> > > 
> > > 感谢，这十个账号应该没有误判的，但没有必要管这些每日大赛下面的账号， 只需要添加在正常大 V 评论区恶意引流的那一批诈骗号即可，搞黄色的如果在每日大赛下面就不用浪费名额给他们， 因为拉黑这批人并不会提升刷推体验，在保证评论区体验的情况下，黑名单数量越少越好。
> > 
> > 
> > 我就是在大V评论区找的XD
> 
> 哈哈， 那应该是这些账号在两边都发了， 你有时间帮忙审核现有 issue 里的举报吗？
> 
> 参考步骤:
> 
> 1. 把现有的 5 个共享黑名单（1，2，3，5，加急）都屏蔽完，这样就不用重复添加。
> 2. 审核 open 状态的 issue 里的账号，打开账号主页查看简介，回复
> 3. 如果符合（在大 V 评论区 + 恶意引流 + 缅北 Cosplay 诈骗）这几个特征就可以添加到列表 4 里。
> 4. 一个 issue 里的账号全部审核完毕后， 你可以 @ 我过来关 issue。
> 
> 感谢你付出的时间和精力！

好的，星期五晚上我会帮忙处理这个事情。

**Comment by devyujie** [comment]
可以搞个谷歌文档，有权限（被大佬认证过）的人才被允许编辑，然后写个程序读取文档里的内容，在这里搞太乱了

**Comment by daymade** [comment]
> 可以搞个谷歌文档，有权限（被大佬认证过）的人才被允许编辑，然后写个程序读取文档里的内容，在这里搞太乱了

感谢提醒, 现在 issue 是可以用程序解析的, issue 的门槛比 google 文档低一点, 而且是公开的, 所以暂时够用了.

**Comment by CMEPCBHG** [comment]
Sorry，大佬，本来上个星期我是想好好弄一下这个列表的，但是最近家里的事情太多了，都没什么精力和时间去维护了，估计接下来的一段时间也还会这样，所以这个列表我暂时没法维护了，期待一个新的志愿者朋友。实在抱歉。

**Comment by daymade** [comment]
> Sorry，大佬，本来上个星期我是想好好弄一下这个列表的，但是最近家里的事情太多了，都没什么精力和时间去维护了，估计接下来的一段时间也还会这样，所以这个列表我暂时没法维护了，期待一个新的志愿者朋友。实在抱歉。

没关系, 感谢你的付出! 谢谢 @CMEPCBHG

**Comment by aoxu** [comment]
建议把这个问题在 X 上发出来，寻求更大范围的帮助，我可以帮你转发。

**Comment by mrt0mhardy** [comment]
gay圈也有很多网黄骗子能不能加下列表
