### ISSUE TITLE
[Feature Request] add an option to Mute and Block accounts at the same time

### ISSUE THREAD

**Issue by s-kk** [daymade/Twitter-Block-Porn#36]
Due to certain bugs in Twitter mobile client, blocked account could still (partially) show up in the comments. By both blocking and muting the accounts, the bug could be mitigated.

**Comment by daymade** [comment]
Certainly. To manage Twitter API's strict rate limits, we can't concurrently send multiple muting requests. However, by running API calls asynchronously in the background and incorporating client-side throttling—capped at 15 requests per 15-minute timeframe—we can ensure a more secure operation that circumvents Twitter's anti-bot mechanisms.

Contributions to implement this feature in the codebase are welcome.
