### ISSUE TITLE
有个快速找到黄推的办法

### ISSUE THREAD

**Issue by visayafan** [daymade/Twitter-Block-Porn#39]
凡是在类似"每日大赛"这种推特下面回复且回复中包含视频的，100%是黄推。
有没有高手知道怎么代码实现自动获取这些账号？

**Comment by daymade** [comment]
这个方法容易误伤，因为在每日大赛下面回复的并不一定会跑到其他大 V 的评论区引流。

我们是要屏蔽这些 100% 的诈骗犯，如果不来打扰人就由它去吧。

另外，还有一个快速找到黄推的方法， 找到列表里存活时间久的黄推，查看它被添加到了哪些列表，列表里大概率都是黄推。

**Comment by Yvan7123** [comment]
100% 很难做到吧
