### ISSUE TITLE
补充黑名单

### ISSUE THREAD

**Issue by HikariQAQ** [daymade/Twitter-Block-Porn#46]
https://twitter.com/johannasim34000?s=21&t=duChkj1C34DDWLTX8PWd7w

**Comment by edica02** [comment]
https://twitter.com/KSCC10

**Comment by DgHCo3** [comment]
https://twitter.com/i/lists/1702293683071008950
合辑

**Comment by DgHCo3** [comment]
https://x.com/EnjangUsep?s=20
广告https://x.com/summercampclub?s=20
https://x.com/temtawan?s=20
https://x.com/SeptianaT_?s=20
https://x.com/Xiao_1104?s=20
https://x.com/PettyAlfre30867?s=20
https://x.com/TheodoreCa42298?s=20
https://x.com/HeLiang74492?s=20
https://x.com/JaylynJaco35423?s=20
https://x.com/zaarayeamin?s=20
广告https://x.com/binance6thX?s=20
https://x.com/EnjangUsep?s=20
https://x.com/Kblw11?s=20
https://x.com/MExvetrHtHWjhRg?s=20
https://x.com/missy177962650?s=20
https://x.com/Honey14933824?s=20
https://x.com/Queen_34re?s=20
广告https://x.com/BNZCDY?s=20
https://x.com/MarlonJuliana13?s=20
广告https://x.com/AdrianDean96792?s=20
广告https://x.com/ClarethaH27021?s=20
https://x.com/IsraelLowe36774?s=20

**Comment by imnekosama** [comment]
黄推诈骗：
https://twitter.com/missy177962650
https://twitter.com/aqiu876
https://twitter.com/_THE_GOLDEN

**Comment by imtipi** [comment]
https://twitter.com/chuiertu79
https://twitter.com/hot_club_0
https://twitter.com/Nandastr6
https://twitter.com/KSCC10
https://twitter.com/EnjangUsep

**Comment by godzilla0000** [comment]
各种黄推账号：
https://twitter.com/Dateflix_
https://twitter.com/jinghongyipei
https://twitter.com/lyainevan_
https://twitter.com/dudubigass
https://twitter.com/luna0O0yu
https://twitter.com/kkbkkb001
https://twitter.com/MExvetrHtHWjhRg
https://twitter.com/Yangyunkaisile
https://twitter.com/bowwy12689816
https://twitter.com/Parara4444
https://twitter.com/EnjangUsep
https://twitter.com/LouiseWill28040
https://twitter.com/JaylynJaco35423
https://twitter.com/tsustsis

**Comment by godzilla0000** [comment]
https://twitter.com/Queen_34re
https://twitter.com/bIindded
https://twitter.com/famotp
https://twitter.com/new_stronger
https://twitter.com/Nandastr6
https://twitter.com/Han86515178
https://twitter.com/MExvetrHtHWjhRg
https://twitter.com/BrunoPiovani

**Comment by rxliuli** [comment]
https://x.com/JaylynJaco35423/status/1703364299358625868?s=20

**Comment by ASUSlake** [comment]
https://twitter.com/JaylynJaco35423
https://twitter.com/KSCC10
https://twitter.com/KwMdnns
https://twitter.com/VincentNorieg20
https://twitter.com/NydiaAnna5
https://twitter.com/JohnLop16537900
https://twitter.com/KaliR70604
https://twitter.com/BrunoPiovan1

**Comment by huanfe1** [comment]
https://twitter.com/MarlonJuliana13

**Comment by Ixmy1297** [comment]
https://twitter.com/AlexanderB29039

**Comment by wanchao0** [comment]
https://twitter.com/CurvesTeen39672
https://twitter.com/SylviaDutt2
https://twitter.com/IvesArchibald7
https://twitter.com/EnjangUsep
https://twitter.com/lustyzara
https://twitter.com/KSCC10
https://twitter.com/ZT73181442
https://twitter.com/banna29556197
https://twitter.com/NelsonZ40974872
https://twitter.com/bowwy12689816
https://twitter.com/Han86515178
https://twitter.com/SeptianaT_
https://twitter.com/MarkDav32818554

**Comment by blackyao** [comment]
https://twitter.com/Helenawen2
https://twitter.com/SebaatianeDeQu7
https://twitter.com/accforsale10

**Comment by Ixmy1297** [comment]
https://x.com/Menglu___Ya?s=20

**Comment by Ixmy1297** [comment]
https://x.com/acpowafu1993874?s=20（广告）

**Comment by Ixmy1297** [comment]
https://twitter.com/MaxLee1077830

**Comment by Ixmy1297** [comment]
https://x.com/SebaatianeDeQu7?s=20

**Comment by Ixmy1297** [comment]
https://x.com/MarlonJuliana13?s=20

**Comment by Ixmy1297** [comment]
https://x.com/SeptianaT_?s=20
https://x.com/Donois932?s=20

**Comment by Ixmy1297** [comment]
https://x.com/CurvesTeen39672?s=20
https://x.com/porn_teen68792?s=20

**Comment by DgHCo3** [comment]
> https://twitter.com/ixxaxx40
请这位Kan-2023不要往这里倒垃圾了，全是毫无意义的链接

**Comment by DgHCo3** [comment]
> https://twitter.com/desi_aulya https://twitter.com/JANNEKNIGHT11 https://twitter.com/jannukso https://twitter.com/ezzty_imoetz

请这位Kan-2023不要往这里倒垃圾了，大部分都是与黄推无关、毫无意义的

**Comment by DgHCo3** [comment]
列表合集https://twitter.com/i/lists/1702293683071008950

大部分黄推开始主动屏蔽了

**Comment by daymade** [comment]
> 列表合集https://twitter.com/i/lists/1702293683071008950
> 
> 大部分黄推开始主动屏蔽了

可以点击  导出(Export) 把列表下载下来，发到 https://github.com/daymade/Twitter-Block-Porn/tree/master/lists/snapshot 这个文件夹下，就可以固化名单，防止诈骗号越狱

**Comment by rxliuli** [comment]
https://x.com/119_miss/status/1704102996177817963?s=20

**Comment by rxliuli** [comment]
https://x.com/someones88/status/1704055792868208785?s=20

**Comment by rxliuli** [comment]
https://x.com/Swtsexlove03/status/1704067988712755612?s=20

**Comment by rxliuli** [comment]
https://x.com/shayujimu_0/status/1704089298847625566?s=20

**Comment by rxliuli** [comment]
https://x.com/KSCC10/status/1704068856774615375?s=20

**Comment by rxliuli** [comment]
https://x.com/Sexual24hr/status/1704013701999886718?s=20

**Comment by rxliuli** [comment]
https://x.com/KSCC10/status/1703788347859271842?s=20

**Comment by rxliuli** [comment]
https://x.com/119_miss/status/1703836393594618323?s=20

**Comment by daymade** [comment]
@kan-2023  请谨慎举报

**Comment by daymade** [comment]
已添加，感谢各位
