### ISSUE TITLE
能否做一个自动扫描屏蔽的？x.com搜索任意城市名出来的都是这种垃圾账号

### ISSUE THREAD

**Issue by hoky** [daymade/Twitter-Block-Porn#69]
所有黑名单都加上了，但是搜索任意城市名还是出来一大片，防不胜防。

**Comment by daymade** [comment]
不行，这种搜地名的场景自古以来就存在了，现有机制没办法拉黑这么多纯机器人，而且更多人只对评论区的黄推才有强烈诉求。
