### ISSUE TITLE
关于 logo 替换

### ISSUE THREAD

**Issue by albaz64** [daymade/Twitter-Block-Porn#7]
拉黑功能本身很好, 但图标替换还是有点小问题.

感觉把那个文本框提示去掉体验会更好, 此外可以再提供一个黑色的图标看个人习惯替换使用.

这是我之前使用的脚本, 可以参考一下.
```JavaScript
(function () {
    waitForKeyElements(
        'a[aria-label="Twitter"]',
        makeBlueBirdGreatAgain
    );
    waitForKeyElements(
        'div[data-testid="TopNavBar"]',
        makeBlueBirdGreatAgain
    );
    changeFavIcon();

    function changeFavIcon() {
        let v = $('link[rel="shortcut icon"]');
        if (v == null || v.length == 0) return;
        v[0].setAttribute("href", 'https://abs.twimg.com/favicons/twitter.ico');
    }

    function makeBlueBirdGreatAgain(v) {
        if (v == null || v.length == 0) return;
        v[0].getElementsByTagName("path")[0].setAttribute("d", 'M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z')
    }

    function waitForKeyElements(
        selectorTxt,
        actionFunction,
        bWaitOnce,
        iframeSelector
    ) {
        var targetNodes, btargetsFound;

        if (typeof iframeSelector == "undefined") {
            targetNodes = $(selectorTxt);
        } else {
            targetNodes = $(iframeSelector).contents().find(selectorTxt);
        }

        if (targetNodes && targetNodes.length > 0) {
            btargetsFound = true;
            targetNodes.each(function () {
                var jThis = $(this);
                var alreadyFound = jThis.data('alreadyFound') || false;

                if (!alreadyFound) {
                    var cancelFound = actionFunction(jThis);
                    if (cancelFound) {
                        btargetsFound = false;
                    } else {
                        jThis.data('alreadyFound', true);
                    }
                }
            });
        } else {
            btargetsFound = false;
        }

        var controlObj = waitForKeyElements.controlObj || {};
        var controlKey = selectorTxt.replace(/[^\w]/g, "_");
        var timeControl = controlObj[controlKey];

        if (btargetsFound && bWaitOnce && timeControl) {
            clearInterval(timeControl);
            delete controlObj[controlKey]
        } else {
            if (!timeControl) {
                timeControl = setInterval(function () {
                    waitForKeyElements(selectorTxt,
                        actionFunction,
                        bWaitOnce,
                        iframeSelector
                    );
                }, 300);
                controlObj[controlKey] = timeControl;
            }
        }
        waitForKeyElements.controlObj = controlObj;
    }
})()
```

**Comment by daymade** [comment]
1. 你的代码很规范， 我 bonus 那个函数完全是 ChatGPT 4 写的，文本框是我特意要求加上的，因为要刷存在感，虽然有点小 bug（移动鼠标时会有点重叠），但我当它是 feature 了，又不是不能用.jpg
2. 黑色的小鸟长什么样子？如果直接替换了我担心会打破用户固有的认知，你不能直接动用户的东西，除非有明确的理由（换色不算
3. 文本框其实不是为了刷存在感，而是为了明确告诉用户：你的图标被我动过了

**Comment by XYZ-dragon** [comment]
> 1. 你的代码很规范， 我 bonus 那个函数完全是 ChatGPT 4 写的，文本框是我特意要求加上的，因为要刷存在感，虽然有点小 bug（移动鼠标时会有点重叠），但我当它是 feature 了，又不是不能用.jpg
> 2. 黑色的小鸟长什么样子？如果直接替换了我担心会打破用户固有的认知，你不能直接动用户的东西，除非有明确的理由（换色不算
> 3. 文本框其实不是为了刷存在感，而是为了明确告诉用户：你的图标被我动过了

1. 确实有点难受, 鼠标移过去文本框体感上还一卡一卡的.
2. 标签页 logo 还是蓝色的, 但有文本框的那个地方替换成了黑色(不是纯黑, 跑一遍上面的代码就能看到了), 其实图标还有其他颜色, 因为 twitter 本身就提供了多个颜色的主题只是最经典的还是蓝色(
3.  虽然但是, 感觉不需要. 或许可以在第一次启用时给个弹窗提示, 或者添加一个是否替换的开关(话说真的有人喜欢那个 X 吗?

**Comment by daymade** [comment]
> > 1. 你的代码很规范， 我 bonus 那个函数完全是 ChatGPT 4 写的，文本框是我特意要求加上的，因为要刷存在感，虽然有点小 bug（移动鼠标时会有点重叠），但我当它是 feature 了，又不是不能用.jpg
> > 2. 黑色的小鸟长什么样子？如果直接替换了我担心会打破用户固有的认知，你不能直接动用户的东西，除非有明确的理由（换色不算
> > 3. 文本框其实不是为了刷存在感，而是为了明确告诉用户：你的图标被我动过了
> 
> 1. 确实有点难受, 鼠标移过去文本框体感上还一卡一卡的.
> 2. 标签页 logo 还是蓝色的, 但有文本框的那个地方替换成了黑色(不是纯黑, 跑一遍上面的代码就能看到了), 其实图标还有其他颜色, 因为 twitter 本身就提供了多个颜色的主题只是最经典的还是蓝色(
> 3.  虽然但是, 感觉不需要. 或许可以在第一次启用时给个弹窗提示, 或者添加一个是否替换的开关(话说真的有人喜欢那个 X 吗?


1 和 3 的想法很好，可以帮忙改下吗？欢迎 PR！

**Comment by albus64** [comment]
> > > 1. 你的代码很规范， 我 bonus 那个函数完全是 ChatGPT 4 写的，文本框是我特意要求加上的，因为要刷存在感，虽然有点小 bug（移动鼠标时会有点重叠），但我当它是 feature 了，又不是不能用.jpg
> > > 2. 黑色的小鸟长什么样子？如果直接替换了我担心会打破用户固有的认知，你不能直接动用户的东西，除非有明确的理由（换色不算
> > > 3. 文本框其实不是为了刷存在感，而是为了明确告诉用户：你的图标被我动过了
> > 
> > 
> > 
> > 1. 确实有点难受, 鼠标移过去文本框体感上还一卡一卡的.
> > 2. 标签页 logo 还是蓝色的, 但有文本框的那个地方替换成了黑色(不是纯黑, 跑一遍上面的代码就能看到了), 其实图标还有其他颜色, 因为 twitter 本身就提供了多个颜色的主题只是最经典的还是蓝色(
> > 3. 虽然但是, 感觉不需要. 或许可以在第一次启用时给个弹窗提示, 或者添加一个是否替换的开关(话说真的有人喜欢那个 X 吗?
> 
> 1 和 3 的想法很好，可以帮忙改下吗？欢迎 PR！

做了一个最简陋的, 但可惜图标颜色不知道去哪换, 虽然我无所谓就是了(
因为不知道界面怎么写所以干脆用弹窗了, 想去抄设置相关代码发现都很长很乱就放弃了.

**Comment by daymade** [comment]
> > > > 1. 你的代码很规范， 我 bonus 那个函数完全是 ChatGPT 4 写的，文本框是我特意要求加上的，因为要刷存在感，虽然有点小 bug（移动鼠标时会有点重叠），但我当它是 feature 了，又不是不能用.jpg
> > > > 2. 黑色的小鸟长什么样子？如果直接替换了我担心会打破用户固有的认知，你不能直接动用户的东西，除非有明确的理由（换色不算
> > > > 3. 文本框其实不是为了刷存在感，而是为了明确告诉用户：你的图标被我动过了
> > > 
> > > 
> > > 
> > > 1. 确实有点难受, 鼠标移过去文本框体感上还一卡一卡的.
> > > 2. 标签页 logo 还是蓝色的, 但有文本框的那个地方替换成了黑色(不是纯黑, 跑一遍上面的代码就能看到了), 其实图标还有其他颜色, 因为 twitter 本身就提供了多个颜色的主题只是最经典的还是蓝色(
> > > 3. 虽然但是, 感觉不需要. 或许可以在第一次启用时给个弹窗提示, 或者添加一个是否替换的开关(话说真的有人喜欢那个 X 吗?
> > 
> > 
> > 1 和 3 的想法很好，可以帮忙改下吗？欢迎 PR！
> 
> 做了一个最简陋的, 但可惜图标颜色不知道去哪换, 虽然我无所谓就是了(好处就是不依赖 jQuery 了, 我是真的用不来. 另外鸟有点小, 希望可以更大一点. 因为不知道界面怎么写所以干脆用弹窗了, 想去抄设置相关代码发现都很长很乱就放弃了.


@albaz64 不好意思我关闭了 #10 , 我们不要动太多存量的旧代码, 只做两件事情可以吗? 

1. 修复 Logo  替换的文字图标会异常重叠闪烁的问题
2. 添加一个开关(SwitchButton)来开启和关闭替换 Logo , 最好不要用阻断式的操作来请求用户输入.

如果你有其他想法, 欢迎随时和我讨论,  再次感谢你的付出!

**Comment by albaz64** [comment]
> > > > > 1. 你的代码很规范， 我 bonus 那个函数完全是 ChatGPT 4 写的，文本框是我特意要求加上的，因为要刷存在感，虽然有点小 bug（移动鼠标时会有点重叠），但我当它是 feature 了，又不是不能用.jpg
> > > > > 2. 黑色的小鸟长什么样子？如果直接替换了我担心会打破用户固有的认知，你不能直接动用户的东西，除非有明确的理由（换色不算
> > > > > 3. 文本框其实不是为了刷存在感，而是为了明确告诉用户：你的图标被我动过了
> > > > 
> > > > 
> > > > 
> > > > 1. 确实有点难受, 鼠标移过去文本框体感上还一卡一卡的.
> > > > 2. 标签页 logo 还是蓝色的, 但有文本框的那个地方替换成了黑色(不是纯黑, 跑一遍上面的代码就能看到了), 其实图标还有其他颜色, 因为 twitter 本身就提供了多个颜色的主题只是最经典的还是蓝色(
> > > > 3. 虽然但是, 感觉不需要. 或许可以在第一次启用时给个弹窗提示, 或者添加一个是否替换的开关(话说真的有人喜欢那个 X 吗?
> > > 
> > > 
> > > 1 和 3 的想法很好，可以帮忙改下吗？欢迎 PR！
> > 
> > 
> > 做了一个最简陋的, 但可惜图标颜色不知道去哪换, 虽然我无所谓就是了(好处就是不依赖 jQuery 了, 我是真的用不来. 另外鸟有点小, 希望可以更大一点. 因为不知道界面怎么写所以干脆用弹窗了, 想去抄设置相关代码发现都很长很乱就放弃了.
> 
> @albaz64 不好意思我关闭了 #10 , 我们不要动太多存量的旧代码, 只做两件事情可以吗?
> 
> 1. 修复 Logo  替换的文字图标会异常重叠闪烁的问题
> 2. 添加一个开关(SwitchButton)来开启和关闭替换 Logo , 最好不要用阻断式的操作来请求用户输入.
> 
> 如果你有其他想法, 欢迎随时和我讨论, 再次感谢你的付出!

折腾了一下, 懒得弄了. 关键代码给你自己弄吧.
至于开关功能, 做不到. 在页面上显示一个按钮很丑, 但可以在输入后自动刷新一次.

```
    // ico 写死在页面里, 直接替换就行
    document.querySelector('head>link[rel="shortcut icon"]').setAttribute('href', 'https://abs.twimg.com/favicons/twitter.ico')

    const textbox = document.createElement('div');
    textbox.className = 'textbox';
    textbox.textContent = 'By twitter block porn script'; // 设置文本内容
    // 添加样式
    textbox.style.position = 'fixed';
    textbox.style.backgroundColor = '#f0f0f0';
    textbox.style.padding = '10px';
    textbox.style.borderRadius = '5px';
    textbox.style.userSelect = 'none';
    // textbox.style.transition = 'transform .15s ease-out'; // 注释掉，如果不需要过渡效果
....
      twitterLogo.addEventListener('mouseenter', () => { textbox.style.display = 'block' })
      twitterLogo.addEventListener('mousemove', (e) => { const x = e.clientX - textbox.offsetWidth / 2; const y = e.clientY - textbox.offsetHeight / 2; textbox.style.transform = `translate(${x}px, ${y}px)` });
      twitterLogo.addEventListener('mouseleave', () => { textbox.style.display = 'none' })
```

**Comment by albaz64** [comment]
> 感谢提供思路和参考代码🙏，这个功能已经随着另外一个 PR #13 上线，非常感谢你的付出，我给项目添加了[贡献名单](https://github.com/daymade/Twitter-Block-Porn#%E8%B4%A1%E7%8C%AE%E8%80%85contributors)，如果你有进一步的想法，欢迎与我交流 🫶

为什么你说话感觉一股机翻味啊.
感谢, 另外这个问题已经解决了我会关闭这个 issue.
